### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Nariusss** [portra400nc/ModelChanger#11]
How does the search work?

**Comment by portra400nc** [comment]
It searches for NPCs and monsters that are currently in the scene. Clicking on a search result will get its model and replace your current character's model with it.  As long as you can see an NPC or a monster, you can search them. So if you want to search for Dainsleif, for example, you have to be in an area/scene where Dainsleif is present.

**Comment by Nariusss** [comment]
Thanks for the answer
