### ISSUE TITLE
Some NPC "Story i think?" bugs

### ISSUE THREAD

**Issue by MAnggiarMustofa** [portra400nc/ModelChanger#14]
![Screenshot (247)](https://user-images.githubusercontent.com/65075830/169687689-376f722b-ce61-43f9-8b27-12a9125d2e70.png)
modelchanger 0.0.8 on NPC Story Mode (Dainsleif)
![20220521002425](https://user-images.githubusercontent.com/65075830/169687827-45b93034-6676-40fd-89df-1c49e97c2b9e.png)
modelchanger 0.0.5 on NPC Story Mode (Dainsleif)

when i try to swap npc story example like Dainsleif it's really work on version 0.0.8 but i don't know why he's really buggy than version 0.0.5
also some npc like scaramouche have same issue like that

**Comment by portra400nc** [comment]
Works fine to me
![GenshinImpact_2022-05-22_20-54-06](https://user-images.githubusercontent.com/102507002/169696218-2ac88d64-a1e5-4443-8c28-ba7a832337b9.jpg)

**Comment by MAnggiarMustofa** [comment]
> Works fine to me ![GenshinImpact_2022-05-22_20-54-06](https://user-images.githubusercontent.com/102507002/169696218-2ac88d64-a1e5-4443-8c28-ba7a832337b9.jpg)

okay maybe i need reinstall my grasscutter thanks for info, anyway could you make the npc or boss can't gone the data when we doing anywhere? (example like on Domain or Teleport) so we can swap there

**Comment by portra400nc** [comment]
Yeah I want that as well. Hopefully I figure that out soon.
