### ISSUE TITLE
how can we change the texture?

### ISSUE THREAD

**Issue by sentirxo** [portra400nc/ModelChanger#17]

**Comment by portra400nc** [comment]
You can get textures in [GI_Textures.](https://github.com/zeroruka/GI_Textures/)

Create a folder called `tex_test` inside `\GenshinImpact_Data` and place your textures in there.
Click `Scan` in the GUI to scan the directory. Clicking on a texture file will replace your current character's texture depending on the array index (0 = hair, 1 = body, 2 = dress). As for the glider, keep the array index at 0.
