### ISSUE TITLE
Does it support 3rd party model? If so, Which type of format is supported? 

### ISSUE THREAD

**Issue by shenmo7192** [portra400nc/ModelChanger#22]
I think this repository need a readme....

I've found some 3rd party model in the format of .pmx, don't know if can load in the game.

Since it's a complex process to set up Grasscutter, I'd like to ask it before I actually set up...

**Comment by shenmo7192** [comment]
New to Unity game mod, sorry if I bother....

**Comment by portra400nc** [comment]
no this mod doesn't support 3rd party models, it doesn't have an importer feature either. you have to rig the imported model manually to a character.

**Comment by shenmo7192** [comment]
> no this mod doesn't support 3rd party models, it doesn't have an importer feature either. you have to rig the imported model manually to a character.

Any clue of importing model? I googled but the results are all about how to import model to blender/mmd etc.....

**Comment by portra400nc** [comment]
dm me on discord portra#3319

**Comment by shenmo7192** [comment]
> 

I'm shenmo#2364. Friend request sent. I'm not an English Native Speaker and I don't know what "dm me" mean so I sent an friend request
