### ISSUE TITLE
please accept my friend request...

### ISSUE THREAD

**Issue by shenmo7192** [portra400nc/ModelChanger#23]
Sorry for bothering, but I was stuck in Phone number vertify and finally my original account cannot login at all...
Discord refuse to send vertify SMS to Chinese Phone number (+86)......
And I found that I lost the server...
I cannot find another way of contact you, so I submit a new issue
I got  a new account in the help of a friend

So please accept my friend request from shenmo7192#0748 when it is a convenient time for you (With the greatest sincerity）

**Comment by portra400nc** [comment]
done
